# Generated by Django 4.1.3 on 2023-02-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='itemNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
